# Generated by Django 5.1.1 on 2024-10-13 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('day', models.DateField(null=True)),
                ('number_of_people', models.IntegerField(default=0)),
                ('watering_garden', models.CharField(default='', max_length=255)),
                ('cooking', models.CharField(default='', max_length=255)),
                ('dishwashing', models.CharField(default='', max_length=255)),
                ('laundry', models.CharField(default='', max_length=255)),
                ('showers', models.CharField(default='', max_length=255)),
                ('toilet_flush', models.CharField(default='', max_length=255)),
                ('total', models.TextField(default='')),
                ('total_daily', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
